### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by niftylettuce** [hthetiot/node-snowball#19]
Full stack trace:

```sh
Module did not self-register: '/var/www/production/source/node_modules/node-snowball/build/Release/snowball.node'.
Error: Module did not self-register: '/var/www/production/source/node_modules/node-snowball/build/Release/snowball.node'.
   at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
   at Module.load (internal/modules/cjs/loader.js:986:32)
   at Function.Module._load (internal/modules/cjs/loader.js:879:14)
   at Module.require (internal/modules/cjs/loader.js:1026:19)
   at require (internal/modules/cjs/helpers.js:72:18)
   at Object.<anonymous> (/var/www/production/source/node_modules/node-snowball/index.js:1:16)
   at Module._compile (internal/modules/cjs/loader.js:1138:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
   at Module.load (internal/modules/cjs/loader.js:986:32)
   at Function.Module._load (internal/modules/cjs/loader.js:879:14)
   at Module.require (internal/modules/cjs/loader.js:1026:19)
   at require (internal/modules/cjs/helpers.js:72:18)
   at Object.<anonymous> (/var/www/production/source/node_modules/spamscanner/index.js:38:18)
   at Module._compile (internal/modules/cjs/loader.js:1138:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
   at Module.load (internal/modules/cjs/loader.js:986:32)
   at Function.Module._load (internal/modules/cjs/loader.js:879:14)
   at Module.require (internal/modules/cjs/loader.js:1026:19)
   at require (internal/modules/cjs/helpers.js:72:18)
   at Object.<anonymous> (/var/www/production/source/node_modules/forward-email/index.js:11:21)
   at Module._compile (internal/modules/cjs/loader.js:1138:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

**Comment by niftylettuce** [comment]
Using latest Node.js v12 LTS and installing with npm.

**Comment by rm-hull** [comment]
Which OS ?

**Comment by niftylettuce** [comment]
Ubuntu 18.04 LTS

**Comment by niftylettuce** [comment]
Does this help? https://stackoverflow.com/a/46935984

**Comment by niftylettuce** [comment]
Trying the rebuild method now..

**Comment by niftylettuce** [comment]
That did not work. I also reproduced this issue on macOS just now!

```sh
✖  error     Error: Module did not self-register: '/Users/user/Projects/forwardemail.net/node_modules/node-snowball/build/Release/snowball.node'.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/user/Projects/forwardemail.net/node_modules/node-snowball/index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/user/Projects/forwardemail.net/node_modules/spamscanner/index.js:38:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/user/Projects/forwardemail.net/node_modules/forward-email/index.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

**Comment by niftylettuce** [comment]
I think we need to swap this order, testing now:

```
            "sources": [
                "src/snowball.cpp",
                "src/NativeExtension.cpp",
```

**Comment by niftylettuce** [comment]
That didn't fix it, per StackOverflow suggestion...

**Comment by niftylettuce** [comment]
Actually, I may have needed to run `npm rebuild` after changing the order, testing again!

**Comment by niftylettuce** [comment]
That didn't work 😢

**Comment by rm-hull** [comment]
The build runs on a weekly crown job in travis, and I just ran a rebuild which has completed ok, see https://travis-ci.org/github/hthetiot/node-snowball/builds

Let me try it on one of the projects I have used it on...

What version of npm and gcc are you using?

**Comment by niftylettuce** [comment]
```sh
~/Projects/forward-email master*
❯ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

~/Projects/forward-email master*
❯ node --version
v12.18.0
```

**Comment by niftylettuce** [comment]
I think the issue is when this package is a package used in a package, or one two or three levels deep.

**Comment by niftylettuce** [comment]
That's not it.  I still get the error.

**Comment by niftylettuce** [comment]
This happens on both macOS and also on a fresh Ubuntu 18.04 LTS server.  This isn't on my side.

**Comment by niftylettuce** [comment]
Actually, I wonder if it's happening because it's being spawned from a Node.js worker thread....  that might be it.

**Comment by niftylettuce** [comment]
A-ha!!! It is.  This is the issue. https://github.com/nodejs/node/issues/21783#issuecomment-429637117

**Comment by niftylettuce** [comment]
PR inbound

**Comment by niftylettuce** [comment]
@rm-hull feel free to merge #20 and release 🎉
